### PR TITLE
Fix write tests

### LINKED ISSUE #15: Update to data_pipeline_api 0.6.0
Currently we are fixed to 0.5.0 which is out of date

### PR DESCRIPTION
**Pull request by sdl1**
Write to a new file, then read back to check. This means we can test the HDF5 write methods.

Also closes #15

### CODE REVIEW

File: test/pyapi.jl [hunk 1]
```diff
@@ -2,50 +2,56 @@
...
-            @test read_sample(api, "parameter", "example-samples") ∈ [9, 10, 11]
+            @test_throws Exception read_estimate(api, "parameter-write", "example-samples")
+            write_samples(api, "parameter-write", "example-samples", [9, 10, 11])
+            @test read_sample(api, "parameter-write", "example-samples") ∈ [9, 10, 11]
 
+            @test_throws Exception read_estimate(api, "object-write", "example-table")
             df = DataFrame(:a => [9, 10], :b => [11, 12])
-            write_table(api, "object", "example-table", df)
-            @test_broken read_table(api, "object", "example-table") == df
+            write_table(api, "object-write", "example-table", df)
```
Comment (AlexRobson) [inline test/pyapi.jl:41]: Is the renaming functionally necessary or just for clarity?

Comment (sdl1) [reply test/pyapi.jl:41]: It means the write will go to the file defined by `object-write/example-table` in `metadata.yaml` (which doesn't exist, so it will create it). I think it's a bit clearer to separate them, also the fix in data_pipeline_api for over-writing isn't released yet.

Comment (AlexRobson) [reply test/pyapi.jl:41]: OK. What i was going towards is whether an additional test is needed to test whether changes are expected (or not) if it already exists, i.e. would the `write` function indeed do an update if the file already exists. If the fix is coming in the pipeline no worries. I thought in that case it was a deliberate choice to not include write functions as part oft he same session. Not sure though.

Comment (sdl1) [reply test/pyapi.jl:41]: Ah ok, yeah I just checked and that still fails:
```julia
write_estimate(api, "parameter-read", "example-estimate", 99.0)
@test read_estimate(api, "parameter-read", "example-estimate") == 99.0
...
Write API: Test Failed at /Users/sean/github/SimulationData.jl/test/pyapi.jl:30
  Expression: read_estimate(api, "parameter-read", "example-estimate") == 99.0
   Evaluated: 1.0 == 99.0
```
I think the intention is to write stuff out in the same api session, you can write to arbitrary files, but to read them back in with the api you need corresponding entries in `metadata.yaml` (which are not generated automatically AFAIK). Here I've just put those entries in manually so we can easily check the writes succeed.

Comment (sdl1) [reply test/pyapi.jl:41]: I think this PR may fix the updating case: https://github.com/ScottishCovidResponse/data_pipeline_api/pull/60

We can try it when there is a new `data_pipeline_api` release

Comment (AlexRobson) [reply test/pyapi.jl:41]: Cool makes sense. Hope that the version is bumped there otherwise we wont' pick it up (doesn't look like the version is incremented, maybe they tend to do that in subsequent MRs)

Comment (AlexRobson) [reply test/pyapi.jl:41]: Speaking of, we probably need a version bump for this too.

File: deps/build.jl [hunk 2]
```diff
@@ -6,4 +6,4 @@ using Conda
 
 pip = joinpath(Conda.BINDIR, "pip")
 run(`$pip install pyyaml setuptools-scm`)
-run(`$pip install git+https://github.com/ScottishCovidResponse/data_pipeline_api@0.5.0`)
+run(`$pip install git+https://github.com/ScottishCovidResponse/data_pipeline_api@0.6.0`)
```
Comment (AlexRobson) [inline deps/build.jl:9]: The PRoject.toml version could be bumped to 0.6.0 to match data_pipeline_api (it's 0.4.0 atm), not sure what best practice is when doing a wrapper, probably it doesn't make sense to match  in general. 

However, think you do need to bump the version otherwise Simulation.jl won't see the changes, i gues to 0.4.1 as the API hasn't actually changed ?

**Comment by AlexRobson** [comment]
Looks good to merge (i'd say bump the version though as discussed).

File: deps/build.jl (hunk 2 above)
Comment (sdl1) [reply deps/build.jl:9]: Yep good catch, bumped to 0.4.1
